sequenceDiagram

participant browser
participant server


browser->>server:  POST https://studies.cs.helsinki.fi/exampleapp/new_note
activate server
server->>browser: Redirects to https://studies.cs.helsinki.fi/exampleapp/notes
deactivate server 

Note left of browser: After the server returns a 200 OK response, it proceeds to redirect
browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
server->>browser: [{content: "a", date: "2023-12-30T02:33:51.039Z"},…]
